pipeline {
    agent any

    environment {
        // Defining environment variables
        ENV_VAR1 = 'value1'                // Simple variable
        ENV_VAR2 = "defaultValue-${params.STRING_PARAM}" // Using parameters within environment variables
    }

    parameters {
        string(name: 'STRING_PARAM', defaultValue: 'defaultString', description: 'This is a string parameter')
        booleanParam(name: 'BOOLEAN_PARAM', defaultValue: true, description: 'This is a boolean parameter')
        choice(name: 'CHOICE_PARAM', choices: ['Option1', 'Option2', 'Option3'], description: 'This is a choice parameter')
        text(name: 'TEXT_PARAM', defaultValue: 'Default text', description: 'This is a text parameter')
        password(name: 'PASSWORD_PARAM', description: 'This is a password parameter')
        file(name: 'FILE_PARAM', description: 'This is a file parameter')
        run(name: 'RUN_PARAM', description: 'Select a specific run of another job')
        credentials(name: 'CREDENTIALS_PARAM', description: 'This is a credentials parameter')
    }

    stages {
        stage('Display Environment and Parameters') {
            steps {
                script {
                    // Accessing parameters
                    echo "String Parameter: ${params.STRING_PARAM}"
                    echo "Boolean Parameter: ${params.BOOLEAN_PARAM}"
                    echo "Choice Parameter: ${params.CHOICE_PARAM}"
                    echo "Text Parameter: ${params.TEXT_PARAM}"
                    echo "Password Parameter: ${params.PASSWORD_PARAM}"
                    echo "File Parameter Path: ${params.FILE_PARAM}" // Path to uploaded file
                    echo "Run Parameter: ${params.RUN_PARAM}"
                    echo "Credentials Parameter: ${params.CREDENTIALS_PARAM}"

                    // Accessing environment variables
                    echo "Environment Variable ENV_VAR1: ${env.ENV_VAR1}"
                    echo "Environment Variable ENV_VAR2: ${env.ENV_VAR2}"
                }
            }
        }
    }
}
