pipeline{
    agent any
    environment{
        AWS_REGION = ""
        S3_BUCKET = ""
        LAMBDA_FUNCTION_NAME = ""
    }
    stages{
        stage('Git CheckOut'){
            steps{
                 git branch: 'main', url: 'https://github.com/pgr-automation/Lambda_Functions.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                // Install dependencies (if using Python)
                sh"""
                touch requirements.txt
                pip install -r requirements.txt -t .
                """
            }
        }
    }
}