pipeline{
    agent any
    environment {
        IMAGE_TAG = "${Build_Tag}"
        VALUES_FILE = "demo-gitops/values-production.yaml"
        TEMP_FILE = 'demo-gitops/temp-values.yaml'
        
    }
    
    stages{
        
        stage('Git check Out'){
            steps{
                script{
                    git branch: 'main', credentialsId: '28059df9-d0e4-49f6-9da6-e410f9470aff', url: 'https://github.com/pgr-automation/GitOps_Demo_Project.git'
                }
             }
        }
        stage('Update Values'){
            steps{
                script{
                   if (!fileExists(VALUES_FILE)) {
                        error "File ${VALUES_FILE} does not exist!"
                    }

                    // Read the existing YAML
                    def valuesFile = readYaml file: VALUES_FILE
                    echo "Current content of ${VALUES_FILE}: ${valuesFile}"

                    // Update the `image.tag` field
                    if (valuesFile.image?.tag) {
                        echo "Updating image.tag from ${valuesFile.image.tag} to ${IMAGE_TAG}."
                        valuesFile.image.tag = IMAGE_TAG
                    } else {
                        error "Field 'image.tag' does not exist in ${VALUES_FILE}!"
                    }

                    // Write the updated content to a temporary file
                    writeYaml file: TEMP_FILE, data: valuesFile
                    echo "Updated content written to temporary file: ${TEMP_FILE}"

                    // Replace the original file with the updated file
                    sh "cp ${TEMP_FILE} ${VALUES_FILE}"
                    echo "Replaced ${VALUES_FILE} with updated content."
                    }
            
                }
            }
        }
            
}



